---
title: "Analysis of Plot"
author: "Vitovsky"
date: "May 30, 2016"
output: 
  html_document:
    keep_md: TRUE
---

##Analysis of Sales Price by Square Footage
After plotting the square footage by sales price, we see that:

  * the highest sales for 1-, 2-, and 3- family homes were also the largest.
  
  * while the most expensive home were the largest, in general, the data seem spread out enough that there might be another factor that would play into the home price.  We are curious to know if the quarter in with the home was sold or the zip code have as much as if not more of a role in the sales price of a home in Manhattan.
  
  * the lowest sale prices did not belong to the smallest homes.  This supports our second point above.
  
  * even though there is a diverse array of data points, the prices seem to be most concentrated in the middle of the graph, the log of square footage falling between 8-8.5, and the log of sales price lying between 15-16.  We added mean (red) and median (blue) points to illustrate this. 
  
  * it seems that one would would have needed a budget of at least $1.5 million in 2015 to begin to be able to afford a 1300 square foot home.
  
  * to buy the average size home, 3,700 square feet, one needs about $3.5 million.
  
  * the median and mean are very close to each other, which gives us beginning indication that the data are normally distributed.
  
In summary, Manahttan is a relatively expensive place to live, but there is enough variability in the data that there is an array of options at different price points for those who have at least $750,000 or so to spend.  While square footage played a role in home price generally, the relationship seems to be additionally impacted by other factors, given that there are still a considerable number of more expensive homes in the lower square footage areas.

``` {r Outliers echo=FALSE}
MSales.homes$outliers <- (log(MSales.homes$sale.price.n) <=5) + 0
MSales.homes <- MSales.homes[which(MSales.homes$outliers==0),]
x <- mean(log(MSales.homes$gross.sqft))
y <- mean(log(MSales.homes$sale.price.n))
x2 <- median(log(MSales.homes$gross.sqft))
y2 <- median(log(MSales.homes$sale.price.n))
plot(log(MSales.homes$gross.sqft),log(MSales.homes$sale.price.n),main = "Home Sales by Square Footage", ylab = "Sales Price", xlab = "Gross Square Feet")
points(x, y, pch = 19, col = "red")
points(x2, y2, pch = 19, col = "blue")
```
