---
title: "RollingSales_Manhattan_Paper"
author: Russell Anderwald; Alex Frye; Christopher Farrar; Lindsay Vitovsky
output: 
  html_document:
    keep_md: TRUE
---

```{r DefineDirectory, include=FALSE}
##Change this path per your project root directory on your machine if you wish to regen the RollingSales_Manhattan_Paper.HTML file
DefaultDir<-"D:/Documents/School/SMU/2016 Summer/MSDS 6306 - Into to Data Science/Assignments/Week 3/Live Session/Live_Session_3_Project"

DataDir<-paste(DefaultDir,"/Data",sep = "")
AnalysisDir<-paste(DefaultDir,"/Analysis",sep = "")
```

#Data Cleanup Tasks

``` {r data, child = paste(DataDir,"/rollingsales_manhattan_Clean_Up_Frye.rmd",sep = "")}
```

#Data Analysis Tasks

``` {r Analysis, child = paste(AnalysisDir,"/MSDS6306_402_GroupHW_Wk3.rmd",sep = "")}
```

``` {r testttt}
MSales.sale$outliers <- (log(MSales.sale$sale.price.n) <=5) + 0
MSales.sale <- MSales.sale[which(MSales.sale$outliers==0),]
plot(log(MSales.sale$gross.square.feet),log(MSales.sale$sale.price.n),main = "Home Sales by Square Footage", ylab = "Sales Price", xlab = "Gross Square Feet")
```
